[phases.setup]
cmds = ["echo 'Setting up environment...'"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed!'"]

[start.cmd]
command = "python main.py"